version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive
  exclusions:
    generated: strict
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: strict

